cabal-version:      3.0
name:               forester-blocks
version:            0.1.0.0
license:            BSD-3-Clause
license-file:       LICENSE
author:             Brent Yorgey
maintainer:         byorgey@gmail.com
copyright:          Brent Yorgey 2026
category:           Text
build-type:         Simple
extra-doc-files:    CHANGELOG.md

common warnings
    ghc-options: -Wall

executable shake
    import:           warnings
    main-is:          Shake.hs
    build-depends:    base ^>=4.21.0.0, shake, text, mtl, hashable, split, diagrams-lib, diagrams-builder, diagrams-rasterific, diagrams-contrib
    default-language: Haskell2010
